Add gnupg config

diff --git a/perl/files/backup b/perl/files/backup
--- a/perl/files/backup
+++ b/perl/files/backup
@@ -5,7 +5,7 @@ FORT="/data/fort"
 NAME="vault"
 VLT="${SAFE}/${NAME}"
 BKP="${FORT}/backup"
-STG="${SAFE}/stage"
+STG="${HOME}/stage"
 MNT="${HOME}/${NAME}"
 
 STP="$(date +%y%m%d%H%M)"
@@ -24,7 +24,7 @@ function glyph {
   echo "info: glyphs"
 
   if ! ls $STG $MNT $SAFE &>/dev/null; then
-    echo "error: directories"
+    echo "error: directories missing"
     exit 1
   fi
 
@@ -36,25 +36,27 @@ function glyph {
   local crypt=${file}.asc
 
   if ! mountpoint -q $MNT; then
-    echo "error: vault is NOT mounted for backup"
+    echo "error: vault not mounted"
     exit 1
   fi
 
   cd $MNT
   if [[ $(pwd) != $MNT ]] || [[ ! -d $name ]]; then
-    echo "error: $name is not found"
+    echo "error: $name not found"
     exit 1
   fi
 
   tar -cJf $file $name
   if [[ $? != 0 ]] || [[ ! -f $file ]]; then
-    echo "error: tar file"
+    echo "error: archive file"
     exit 1
   fi
 
-  gpg -ca $file
+  gpg -sea $file
   if [[ $? != 0 ]] || [[ ! -f $crypt ]] || [[ ! -s $crypt ]]; then
-    echo "error: gpg file"
+    echo "error: encrypt file"
+    rm -f $file $crypt
+    exit 1
   else  
     cat $crypt
     mv $crypt ${STG}/${crypt}
@@ -62,8 +64,10 @@ function glyph {
 
   if [[ -f ${STG}/${crypt} ]]; then
     echo "info: success"
+  else
+    echo "error: move $crypt"
   fi
-  rm -f $file
+  rm -f $file $crypt
 }
 
 function backup {
@@ -100,7 +104,7 @@ function restore {
   echo "info: restore"
 
   if ! ls $BKP &>/dev/null; then
-    echo "error: directories"
+    echo "error: directories missing"
     exit 1
   fi
 
@@ -116,9 +120,9 @@ function restore {
   local save=0
   local res=0
 
-  if [[ ! -z $name ]] && [[ -d $name ]]; then
+  if [[ -d $name ]]; then
     echo "warn: vault present: save"
-    mv $name ${NAME}.${STP}.save
+    mv $name ${name}.save
     if [[ $? != 0 ]]; then
       echo "error: save vault"
       exit 1
@@ -132,9 +136,9 @@ function restore {
   if [[ ! -d $VLT ]]; then
     echo "error: restore $first"
     if [[ $save == 1 ]]; then
-      echo "info: restore back saved"
+      echo "info: restore saved"
       if [[ ! -d $name ]]; then
-        mv ${NAME}.${STP}.save $name
+        mv ${name}.save $name
       fi
     fi
   else
